@startuml

' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "aircraft" as aircraft {
  *aircraftName : string <<PK>>
  --
  *registerId : string
  *aircraftType : string
  *aircraftMTOW : int
}

entity "battery" as battery {
  *serialId : string <<generated>>
  --
  *batteryType : string
  *batterySize : int
  *batteryId : int
  *batteryCell : int
}

entity "person" as operator {
  *id : int <<PK>> <<generated>>
  --
  *name : string 
  *phoneNumber : int
  *teamName : string
  *position : string
  *certification : string
}

entity "flightOperator" as flightOperator {
  *flightDataId : int <<FK>>
  *operatorId : int <<FK>>
  --
  *flightOperatorId : person <<PK>> 
  *role : EP / IP / obserser
}

entity "flightData" as flightPlan {
  *id : int <<generated>>
  --
  *aircraftName : aircraft <<FK>>
  *serialId : List<battery> <<FK>>
  *batteryUsage : int
  *flightDate : zondDateTime
  *windSpeed : int
  *windDirection : int
  *humidity : int
  *temperature : int
  *flightTime : int
  *payloadItem : string
  *payloadWeight : int
}



flightPlan ||--o{ flightOperator
operator ||--o{ flightOperator

battery }o--|| flightPlan
aircraft }o--|| flightPlan


@enduml
