@startuml

' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "Aircraft" as e01{
  *aircraftRegisterNumber : <<PK>> string
  --
  *aircraftName : string
  *aircraftType : string
  *mtow : int
}

entity "Battery" as e02 {
  *batteryId : <<PK>> number
  --
  *capacity : int
  *cellNum : int
  *batteryType : string
  *serialNumber : string
}

entity "Payload" as e03 {
  *id : <<PK>> number (generated)
  --
  *paylodType : string 
  *payloadWeight : int
}


@enduml
