@startuml

' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "aircraft" as e01 {
  *aircraftName : string <<PK>>
  --
  *registerId : string
  *aircraftType : string
  *aircraftMTOW : int
}

entity "battery" as e02 {
  *serialId : string <<generated>>
  --
  *batteryType : string
  *batterySize : int
  *batteryId : int
  *batteryCell : int
}

entity "operator" as e03 {
  *id : int <<PK>> <<generated>>
  --
  *operatorName : string <<generated>>
  *operatorType : string(EP / IP)
  *phoneNumber : int
  *teamName : string
  *position : string
  *certification : string
}

entity "flight_log" as e04 {
  *id : int <<generated>>
  --
  *aircraftName : aircraft <<FK>>
  *serialId : List<battery> <<FK>>
  *batteryUsage : int
  *flightDate : zondDateTime
  *windSpeed : int
  *windDirection : int
  *humidity : int
  *temperature : int
  *operatorEp : operator <<FK>>
  *operatorIP : operator <<FK>>
  *flightTime : int
  *payloadItem : string
  *payloadWeight : int
}



e01 ||-|| e04
e02 }|--|| e04
e03 }|---|{ e04



@enduml
